import { ConfigExtension, DefaultClassGroupIds, DefaultThemeGroupIds } from 'tailwind-merge';

export const tailwindConfig: ConfigExtension<DefaultClassGroupIds, DefaultThemeGroupIds> = {
  extend: {
    theme: {
      breakpoint: ['xs'],
      color: [
        'base',
        'base-raised',
        'base-placeholder-fg',
        'base-overlay',
        'base-overlay-active',
        'base-overlay-hover',
        'base-input',
        'base-input-focus',
        'base-input-on',
        'base-input-off',
        'base-input-disabled',
        'base-border-focus',
        'base-border-input',
        'base-border-input-focus',
        'white-accent-fg',
        'white-hover',
        'white-subtle',
        'white-border-medium',
        'white-border-accent',
        'black-accent',
        'black-accent-fg',
        'primary-accent',
        'primary-accent-fg',
        'primary-subtle',
        'primary-strong',
        'primary-hover',
        'primary-border-medium',
        'neutral-accent',
        'neutral-accent-fg',
        'neutral-subtle',
        'neutral-subtle-fg',
        'neutral-body-fg',
        'neutral-medium',
        'neutral-dimmed',
        'neutral-hover',
        'neutral-body-minimal',
        'neutral-border-medium',
        'neutral-border-subtle',
        'neutral-border-strong',
        'positive-subtle',
        'positive-strong',
        'positive-accent',
        'positive-accent-fg',
        'negative-accent',
        'negative-accent-fg',
        'negative-dimmed',
        'negative-subtle',
        'negative-hover',
        'negative-strong',
        'negative-border-medium',
        'negative-border-strong',
        'negative-border-accent',
        'info-accent',
        'info-accent-fg',
        'info-subtle',
        'info-strong',
        'notice-subtle',
        'notice-accent-fg',
        'inverse-accent',
        'inverse-accent-fg',
        'inverse-subtle',
        'inverse-hover',
        'inverse-border-medium',
        'inverse-border-strong'
      ],
      text: [
        'label',
        'detail',
        'small',
        'micro',
        'nano'
      ]
    }
  }
};
